image: node:alpine

cache:
  paths:
    - backend/node_modules
    - frontend-react/node_modules
    - ~/.cache/Cypress
    - .yarn

stages:
  - install
  - test
  - build
  - deploy

install-backend:
  stage: install
  script:
    - cd backend
    - yarn
  # artifacts:
  #   paths:
  #     - node_modules/
  #   expire_in: 1 week

install-frontend:
  stage: install
  script:
    - cd frontend-react
    - yarn
  # artifacts:
  #   paths:
  #     - node_modules/
  #   expire_in: 1 week

test-backend:
  stage: test
  script:
    - cd backend
    - yarn run test

test-frontend:
  image: cypress/base:14
  stage: test
  script:
    - cd frontend-react
    - yarn run start
    - yarn run test:e2e
