image: node:alpine

cache:
  paths:
    - backend/node_modules
    - frontend-react/node_modules
    - frontend-react/build
    - ~/.cache/Cypress
    - .yarn
    - ~/.config/yarn/global

stages:
  - install
  - test
  - build
  - deploy

install-backend:
  stage: install
  script:
    - cd backend
    - yarn

install-frontend:
  stage: install
  script:
    - cd frontend-react
    - yarn

test-backend:
  stage: test
  script:
    - cd backend
    - yarn run test

test-frontend:
  image: cypress/base:14
  stage: test
  script:
    - yarn global add pm2
    - cd frontend-react
    - yarn run test

build-backend:
  stage: build
  script:
    - cd backend
    - yarn run build
    - cp -R scripts dist
    - cp appspec.yml package.json yarn.lock dist

build-frontend:
  stage: build
  script:
    - cd frontend-react
    - yarn run build
