image: node:latest

cache:
  paths:
    - backend/node_modules
    - frontend-react/node_modules
    - frontend-react/build
    - ~/.cache/Cypress
    - .yarn
    - ~/.config/yarn/global

stages:
  - install
  - build
  - test
  - deploy

install-backend:
  stage: install
  script:
    - cd backend
    - yarn install --cache-folder ../.yarn

install-frontend:
  stage: install
  script:
    - cd frontend-react
    - yarn install --cache-folder ../.yarn

build-backend:
  stage: build
  cache:
    paths:
      - backend/dist
  script:
    - cd backend
    - yarn run build
    - cp -R scripts dist
    - cp appspec.yml package.json yarn.lock dist
  artifacts:
    paths:
      - backend/dist
    expire_in: 1 hour

build-frontend:
  stage: build
  cache:
    paths:
      - frontend-react/build
  script:
    - cd frontend-react
    - yarn run build

# test-backend:
#   stage: test
#   script:
#     - cd backend
#     - yarn run test

test-frontend:
  stage: test
  script:
    - yarn global add pm2
    - pm2 start --name backend backend/dist/server.js
    - cd frontend-react
    - yarn add -D start-server-and-test
    - yarn run test
