image: node:alpine

cache:
  paths:
    - backend/node_modules
    - frontend-react/node_modules
    - frontend-react/build
    - ~/.cache/Cypress
    - .yarn
    - ~/.config/yarn/global

stages:
  - install
  - docker-build
  - test
  - build
  - deploy

install-backend:
  stage: install
  script:
    - cd backend
    - yarn

install-frontend:
  stage: install
  script:
    - cd frontend-react
    - yarn

docker-image-build:
  image: docker:stable
  services:
    - docker:dind
  stage: docker-build
  script:
    - cd backend
    - docker build -t $CI_REGISTRY/helsinki-places/helsinki-places .
    - docker login registry.helsinki-places.com -u nguyenduy010798 -p $DOCKER_ACCESS_TOKEN
    - docker push $CI_REGISTRY/helsinki-places/helsinki-places
# test-backend:
#   stage: test
#   script:
#     - cd backend
#     - yarn run test

# test-frontend:
#   image: cypress/base:14
#   stage: test
#   script:
#     - yarn global add ts-node
#     - cd frontend-react
#     - yarn run test

# build-backend:
#   stage: build
#   script:
#     - cd backend
#     - yarn run build
#     - cp -R scripts dist
#     - cp appspec.yml package.json yarn.lock dist

# build-frontend:
#   stage: build
#   script:
#     - cd frontend-react
#     - yarn run build
