image: node:alpine

cache:
  paths:
    - backend/node_modules
    - frontend-react/node_modules
    - frontend-react/build
    - ~/.cache/Cypress
    - .yarn
    - ~/.config/yarn/global

stages:
  - install
  - docker-build
  - test
  - build
  - deploy

install-backend:
  stage: install
  script:
    - cd backend
    - yarn

install-frontend:
  stage: install
  script:
    - cd frontend-react
    - yarn

docker-image-build:
  image: docker:stable
  services:
    - docker:dind
  stage: docker-build
  script:
    - cd backend
    - docker build -t wyfy/helsinki-places-server .
    - docker login -u wyfy -p $DOCKER_ACCESS_TOKEN
    - docker push wyfy/helsinki-places-server

test-backend:
  stage: test
  script:
    - cd backend
    - yarn run test

test-frontend:
  image: docker:stable
  services:
    - docker:dind
  stage: test
  before_script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  script:
    - docker run -dp 5000:5000 wyfy/helsinki-places-server
    - cd frontend-react
    - yarn run test

build-backend:
  stage: build
  script:
    - cd backend
    - yarn run build
    - cp -R scripts dist
    - cp appspec.yml package.json yarn.lock dist

build-frontend:
  stage: build
  script:
    - cd frontend-react
    - yarn run build
