apiVersion: apps/v1
kind: Deployment
metadata:
  name: helsinki-places-api
  namespace: projects
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helsinki-places-api
  template:
    metadata:
      labels:
        app: helsinki-places-api
    spec:
      containers:
        - name: helsinki-places-api
          image: wyfy/helsinki-places-api:1.0.0
          imagePullPolicy: IfNotPresent
      env:
        - name: NODE_ENV
          value: production
        - name: REDIS_PORT
          values: 6379
        - name: ENDPOINT
          values: redis-svc
        - name: PORT
          values: 5000
