apiVersion: apps/v1
kind: Deployment
metadata:
  name: helsinki-places-api
  namespace: projects
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helsinki-places-api
  template:
    metadata:
      labels:
        app: helsinki-places-api
    spec:
      containers:
        - name: helsinki-places-api
          image: wyfy/helsinki-places-api:1.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: production
            - name: REDIS_PORT
              value: '6379'
            - name: ENDPOINT
              value: redis-svc
            - name: PORT
              value: '5000'
